// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blazor.Data;

#nullable disable

namespace blazor.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107000018_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("blazor.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1133.jpg",
                            Name = "Coy Ullrich",
                            Position = 2,
                            Salary = 4319929m,
                            Type = 1
                        },
                        new
                        {
                            Id = -2,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/867.jpg",
                            Name = "Elsie Green",
                            Position = 4,
                            Salary = 4307633m,
                            Type = 0
                        },
                        new
                        {
                            Id = -3,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1112.jpg",
                            Name = "Britney Emmerich",
                            Position = 5,
                            Salary = 3628785m,
                            Type = 2
                        },
                        new
                        {
                            Id = -4,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/227.jpg",
                            Name = "Lorenzo Carter",
                            Position = 0,
                            Salary = 8335387m,
                            Type = 2
                        },
                        new
                        {
                            Id = -5,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/439.jpg",
                            Name = "Dorian Heaney",
                            Position = 4,
                            Salary = 9130915m,
                            Type = 1
                        },
                        new
                        {
                            Id = -6,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/309.jpg",
                            Name = "Britney Schneider",
                            Position = 2,
                            Salary = 8764144m,
                            Type = 1
                        },
                        new
                        {
                            Id = -7,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/881.jpg",
                            Name = "Simeon Keeling",
                            Position = 3,
                            Salary = 7947813m,
                            Type = 0
                        },
                        new
                        {
                            Id = -8,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/541.jpg",
                            Name = "Olen Langosh",
                            Position = 0,
                            Salary = 6623539m,
                            Type = 2
                        },
                        new
                        {
                            Id = -9,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/596.jpg",
                            Name = "Queen McCullough",
                            Position = 1,
                            Salary = 3528442m,
                            Type = 1
                        },
                        new
                        {
                            Id = -10,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/515.jpg",
                            Name = "Erik Cremin",
                            Position = 1,
                            Salary = 7127180m,
                            Type = 2
                        },
                        new
                        {
                            Id = -11,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/457.jpg",
                            Name = "Wellington Jast",
                            Position = 3,
                            Salary = 1861177m,
                            Type = 3
                        },
                        new
                        {
                            Id = -12,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/595.jpg",
                            Name = "Carlie Kling",
                            Position = 4,
                            Salary = 4698440m,
                            Type = 1
                        },
                        new
                        {
                            Id = -13,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/618.jpg",
                            Name = "Myrtie Harber",
                            Position = 2,
                            Salary = 1988770m,
                            Type = 0
                        },
                        new
                        {
                            Id = -14,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1214.jpg",
                            Name = "Dejuan Barton",
                            Position = 2,
                            Salary = 6108592m,
                            Type = 1
                        },
                        new
                        {
                            Id = -15,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1223.jpg",
                            Name = "Aniyah Bednar",
                            Position = 1,
                            Salary = 3592213m,
                            Type = 1
                        },
                        new
                        {
                            Id = -16,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1142.jpg",
                            Name = "Lenny Shields",
                            Position = 2,
                            Salary = 7152325m,
                            Type = 3
                        },
                        new
                        {
                            Id = -17,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/129.jpg",
                            Name = "Rosella Grimes",
                            Position = 3,
                            Salary = 6644043m,
                            Type = 0
                        },
                        new
                        {
                            Id = -18,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/4.jpg",
                            Name = "Grady Rowe",
                            Position = 1,
                            Salary = 534359m,
                            Type = 1
                        },
                        new
                        {
                            Id = -19,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/759.jpg",
                            Name = "Orie Dickinson",
                            Position = 2,
                            Salary = 2541676m,
                            Type = 3
                        },
                        new
                        {
                            Id = -20,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/473.jpg",
                            Name = "Helene Jacobson",
                            Position = 3,
                            Salary = 7366893m,
                            Type = 0
                        },
                        new
                        {
                            Id = -21,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/725.jpg",
                            Name = "Veronica Jacobson",
                            Position = 2,
                            Salary = 6474355m,
                            Type = 3
                        },
                        new
                        {
                            Id = -22,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1016.jpg",
                            Name = "Kurt Marquardt",
                            Position = 2,
                            Salary = 7770066m,
                            Type = 3
                        },
                        new
                        {
                            Id = -23,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/521.jpg",
                            Name = "Claude Moore",
                            Position = 3,
                            Salary = 4863100m,
                            Type = 3
                        },
                        new
                        {
                            Id = -24,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1238.jpg",
                            Name = "Holly Mills",
                            Position = 2,
                            Salary = 8243415m,
                            Type = 2
                        },
                        new
                        {
                            Id = -25,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/909.jpg",
                            Name = "Aurelie Prohaska",
                            Position = 4,
                            Salary = 5300255m,
                            Type = 1
                        },
                        new
                        {
                            Id = -26,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1094.jpg",
                            Name = "Micheal Bernier",
                            Position = 2,
                            Salary = 530195m,
                            Type = 0
                        },
                        new
                        {
                            Id = -27,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/428.jpg",
                            Name = "Dewayne Jaskolski",
                            Position = 2,
                            Salary = 3091934m,
                            Type = 0
                        },
                        new
                        {
                            Id = -28,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/845.jpg",
                            Name = "Ayana Donnelly",
                            Position = 5,
                            Salary = 7612596m,
                            Type = 0
                        },
                        new
                        {
                            Id = -29,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1086.jpg",
                            Name = "Unique Adams",
                            Position = 1,
                            Salary = 6157749m,
                            Type = 3
                        },
                        new
                        {
                            Id = -30,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/274.jpg",
                            Name = "Bridgette Hackett",
                            Position = 1,
                            Salary = 8253009m,
                            Type = 0
                        },
                        new
                        {
                            Id = -31,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1249.jpg",
                            Name = "Corrine Bernhard",
                            Position = 0,
                            Salary = 1101541m,
                            Type = 3
                        },
                        new
                        {
                            Id = -32,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/607.jpg",
                            Name = "Margie Torp",
                            Position = 2,
                            Salary = 2793518m,
                            Type = 0
                        },
                        new
                        {
                            Id = -33,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1229.jpg",
                            Name = "Isabella Gusikowski",
                            Position = 5,
                            Salary = 1960117m,
                            Type = 1
                        },
                        new
                        {
                            Id = -34,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1169.jpg",
                            Name = "Ericka Zboncak",
                            Position = 1,
                            Salary = 7052739m,
                            Type = 0
                        },
                        new
                        {
                            Id = -35,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/906.jpg",
                            Name = "Carey Borer",
                            Position = 5,
                            Salary = 2801401m,
                            Type = 3
                        },
                        new
                        {
                            Id = -36,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/181.jpg",
                            Name = "Alanis Parisian",
                            Position = 4,
                            Salary = 3671438m,
                            Type = 1
                        },
                        new
                        {
                            Id = -37,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/687.jpg",
                            Name = "Brisa Hudson",
                            Position = 2,
                            Salary = 3314497m,
                            Type = 0
                        },
                        new
                        {
                            Id = -38,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1057.jpg",
                            Name = "Elmer Buckridge",
                            Position = 4,
                            Salary = 8138278m,
                            Type = 0
                        },
                        new
                        {
                            Id = -39,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/711.jpg",
                            Name = "Rosalee Hessel",
                            Position = 2,
                            Salary = 2308831m,
                            Type = 0
                        },
                        new
                        {
                            Id = -40,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1233.jpg",
                            Name = "Callie Roberts",
                            Position = 5,
                            Salary = 5642344m,
                            Type = 0
                        },
                        new
                        {
                            Id = -41,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/269.jpg",
                            Name = "Euna Wehner",
                            Position = 3,
                            Salary = 9648620m,
                            Type = 0
                        },
                        new
                        {
                            Id = -42,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1140.jpg",
                            Name = "Dulce McCullough",
                            Position = 4,
                            Salary = 1530231m,
                            Type = 0
                        },
                        new
                        {
                            Id = -43,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/237.jpg",
                            Name = "Lura Wolf",
                            Position = 5,
                            Salary = 8987756m,
                            Type = 2
                        },
                        new
                        {
                            Id = -44,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/522.jpg",
                            Name = "Celine Hammes",
                            Position = 3,
                            Salary = 2053754m,
                            Type = 1
                        },
                        new
                        {
                            Id = -45,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/216.jpg",
                            Name = "Eda Hodkiewicz",
                            Position = 1,
                            Salary = 1809094m,
                            Type = 2
                        },
                        new
                        {
                            Id = -46,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/88.jpg",
                            Name = "Keshawn Braun",
                            Position = 5,
                            Salary = 7691253m,
                            Type = 0
                        },
                        new
                        {
                            Id = -47,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/847.jpg",
                            Name = "Alvina Hills",
                            Position = 5,
                            Salary = 4759117m,
                            Type = 1
                        },
                        new
                        {
                            Id = -48,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/798.jpg",
                            Name = "Sonia Trantow",
                            Position = 2,
                            Salary = 1083364m,
                            Type = 1
                        },
                        new
                        {
                            Id = -49,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/948.jpg",
                            Name = "Lorenz Davis",
                            Position = 2,
                            Salary = 8922564m,
                            Type = 0
                        },
                        new
                        {
                            Id = -50,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1084.jpg",
                            Name = "Shanelle Pagac",
                            Position = 2,
                            Salary = 9464540m,
                            Type = 2
                        },
                        new
                        {
                            Id = -51,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/562.jpg",
                            Name = "Keon Balistreri",
                            Position = 0,
                            Salary = 549977m,
                            Type = 3
                        },
                        new
                        {
                            Id = -52,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/964.jpg",
                            Name = "Kade Kutch",
                            Position = 3,
                            Salary = 8017950m,
                            Type = 0
                        },
                        new
                        {
                            Id = -53,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/875.jpg",
                            Name = "Liliane Dickinson",
                            Position = 0,
                            Salary = 926688m,
                            Type = 0
                        },
                        new
                        {
                            Id = -54,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/905.jpg",
                            Name = "Johnathan Prohaska",
                            Position = 2,
                            Salary = 997815m,
                            Type = 1
                        },
                        new
                        {
                            Id = -55,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/840.jpg",
                            Name = "Leland Daugherty",
                            Position = 4,
                            Salary = 8956651m,
                            Type = 0
                        },
                        new
                        {
                            Id = -56,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/93.jpg",
                            Name = "Delbert Koss",
                            Position = 2,
                            Salary = 9071377m,
                            Type = 0
                        },
                        new
                        {
                            Id = -57,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/428.jpg",
                            Name = "Nathen Fadel",
                            Position = 5,
                            Salary = 8180028m,
                            Type = 2
                        },
                        new
                        {
                            Id = -58,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/975.jpg",
                            Name = "Aurelio Gutkowski",
                            Position = 3,
                            Salary = 4035263m,
                            Type = 3
                        },
                        new
                        {
                            Id = -59,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/222.jpg",
                            Name = "Hollis Gorczany",
                            Position = 0,
                            Salary = 6488026m,
                            Type = 1
                        },
                        new
                        {
                            Id = -60,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/203.jpg",
                            Name = "Gabrielle Ward",
                            Position = 5,
                            Salary = 8451124m,
                            Type = 3
                        },
                        new
                        {
                            Id = -61,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/638.jpg",
                            Name = "Madaline Weimann",
                            Position = 5,
                            Salary = 6524169m,
                            Type = 3
                        },
                        new
                        {
                            Id = -62,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/37.jpg",
                            Name = "Hildegard Mitchell",
                            Position = 2,
                            Salary = 6097930m,
                            Type = 0
                        },
                        new
                        {
                            Id = -63,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/731.jpg",
                            Name = "Elnora Emard",
                            Position = 4,
                            Salary = 2312164m,
                            Type = 0
                        },
                        new
                        {
                            Id = -64,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/889.jpg",
                            Name = "Candido Koch",
                            Position = 3,
                            Salary = 9233708m,
                            Type = 2
                        },
                        new
                        {
                            Id = -65,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/403.jpg",
                            Name = "Cristopher Kohler",
                            Position = 1,
                            Salary = 2572565m,
                            Type = 2
                        },
                        new
                        {
                            Id = -66,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/287.jpg",
                            Name = "Griffin Howell",
                            Position = 3,
                            Salary = 6174704m,
                            Type = 0
                        },
                        new
                        {
                            Id = -67,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/989.jpg",
                            Name = "Niko Hauck",
                            Position = 5,
                            Salary = 6341934m,
                            Type = 0
                        },
                        new
                        {
                            Id = -68,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/437.jpg",
                            Name = "River Stehr",
                            Position = 5,
                            Salary = 8365579m,
                            Type = 1
                        },
                        new
                        {
                            Id = -69,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/92.jpg",
                            Name = "Rowan Stroman",
                            Position = 3,
                            Salary = 1477829m,
                            Type = 1
                        },
                        new
                        {
                            Id = -70,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/870.jpg",
                            Name = "Angelina Keeling",
                            Position = 1,
                            Salary = 4913644m,
                            Type = 3
                        },
                        new
                        {
                            Id = -71,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/534.jpg",
                            Name = "Odie Howe",
                            Position = 3,
                            Salary = 7985687m,
                            Type = 1
                        },
                        new
                        {
                            Id = -72,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/523.jpg",
                            Name = "Clemmie Prohaska",
                            Position = 1,
                            Salary = 7735173m,
                            Type = 0
                        },
                        new
                        {
                            Id = -73,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/790.jpg",
                            Name = "Tyreek Schaden",
                            Position = 0,
                            Salary = 6556406m,
                            Type = 0
                        },
                        new
                        {
                            Id = -74,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/144.jpg",
                            Name = "Alyson Olson",
                            Position = 2,
                            Salary = 4685282m,
                            Type = 0
                        },
                        new
                        {
                            Id = -75,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/964.jpg",
                            Name = "Maye Lakin",
                            Position = 3,
                            Salary = 7911164m,
                            Type = 3
                        },
                        new
                        {
                            Id = -76,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/723.jpg",
                            Name = "Jack Larkin",
                            Position = 2,
                            Salary = 6010283m,
                            Type = 3
                        },
                        new
                        {
                            Id = -77,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/123.jpg",
                            Name = "Brett Orn",
                            Position = 1,
                            Salary = 6347012m,
                            Type = 2
                        },
                        new
                        {
                            Id = -78,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/371.jpg",
                            Name = "Alfredo Doyle",
                            Position = 3,
                            Salary = 3887328m,
                            Type = 3
                        },
                        new
                        {
                            Id = -79,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1012.jpg",
                            Name = "Sabryna Haley",
                            Position = 3,
                            Salary = 7027057m,
                            Type = 0
                        },
                        new
                        {
                            Id = -80,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/209.jpg",
                            Name = "Perry Sawayn",
                            Position = 4,
                            Salary = 5042245m,
                            Type = 1
                        },
                        new
                        {
                            Id = -81,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/321.jpg",
                            Name = "Roy Powlowski",
                            Position = 3,
                            Salary = 6561985m,
                            Type = 3
                        },
                        new
                        {
                            Id = -82,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/324.jpg",
                            Name = "Oswald Lakin",
                            Position = 3,
                            Salary = 3976887m,
                            Type = 1
                        },
                        new
                        {
                            Id = -83,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/99.jpg",
                            Name = "Yasmine Terry",
                            Position = 5,
                            Salary = 3779090m,
                            Type = 0
                        },
                        new
                        {
                            Id = -84,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/586.jpg",
                            Name = "Austyn Grant",
                            Position = 1,
                            Salary = 765522m,
                            Type = 3
                        },
                        new
                        {
                            Id = -85,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/582.jpg",
                            Name = "Christine Rempel",
                            Position = 2,
                            Salary = 3179363m,
                            Type = 2
                        },
                        new
                        {
                            Id = -86,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/69.jpg",
                            Name = "Natasha Purdy",
                            Position = 5,
                            Salary = 3453083m,
                            Type = 0
                        },
                        new
                        {
                            Id = -87,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/273.jpg",
                            Name = "Albertha Jakubowski",
                            Position = 4,
                            Salary = 6356270m,
                            Type = 2
                        },
                        new
                        {
                            Id = -88,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/347.jpg",
                            Name = "Hillary DuBuque",
                            Position = 5,
                            Salary = 2574132m,
                            Type = 0
                        },
                        new
                        {
                            Id = -89,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/919.jpg",
                            Name = "Rowan Blick",
                            Position = 3,
                            Salary = 8128644m,
                            Type = 3
                        },
                        new
                        {
                            Id = -90,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/480.jpg",
                            Name = "Merlin Collins",
                            Position = 5,
                            Salary = 5360171m,
                            Type = 3
                        },
                        new
                        {
                            Id = -91,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/976.jpg",
                            Name = "Mariela Ankunding",
                            Position = 3,
                            Salary = 6813856m,
                            Type = 0
                        },
                        new
                        {
                            Id = -92,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/819.jpg",
                            Name = "Ethan Bailey",
                            Position = 0,
                            Salary = 6621671m,
                            Type = 0
                        },
                        new
                        {
                            Id = -93,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/452.jpg",
                            Name = "Herminio Wiegand",
                            Position = 5,
                            Salary = 1684414m,
                            Type = 2
                        },
                        new
                        {
                            Id = -94,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/467.jpg",
                            Name = "Melba Trantow",
                            Position = 4,
                            Salary = 1080760m,
                            Type = 1
                        },
                        new
                        {
                            Id = -95,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/830.jpg",
                            Name = "Lane Koss",
                            Position = 2,
                            Salary = 9651366m,
                            Type = 1
                        },
                        new
                        {
                            Id = -96,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/547.jpg",
                            Name = "Davon Hane",
                            Position = 4,
                            Salary = 8224237m,
                            Type = 2
                        },
                        new
                        {
                            Id = -97,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/179.jpg",
                            Name = "Ricky Lind",
                            Position = 2,
                            Salary = 3421262m,
                            Type = 1
                        },
                        new
                        {
                            Id = -98,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1062.jpg",
                            Name = "Roselyn Pagac",
                            Position = 5,
                            Salary = 8866685m,
                            Type = 3
                        },
                        new
                        {
                            Id = -99,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/78.jpg",
                            Name = "Lillian Larson",
                            Position = 4,
                            Salary = 3736210m,
                            Type = 2
                        },
                        new
                        {
                            Id = -100,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/500.jpg",
                            Name = "Scotty Hagenes",
                            Position = 0,
                            Salary = 4399086m,
                            Type = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
